### ISSUE TITLE
calibre 3.48 - how to highlight text in windows 7

### ISSUE THREAD

**Issue by tasnuva1** [al1b/Calibre-KiPEO#16]
I love this tool but I can't just highlight it.

Please, someone, help me....

**Comment by al1b** [comment]
I'm the author of this software. How can I help you?

**Comment by tasnuva1** [comment]
Thank you for reaching out to me. Please, tell me the solution to highlight text in my windows 7. I know, it's really a simple task but there is no future of doing it -in calibre-64bit-3.48.0.

**Comment by al1b** [comment]
You're welcome. Are you using my plugin (KiPEO) or the Calibre itself? I
think you are asking questions about Calibre itself. Unfortunately I
cannot help you with that.

Check this link btw, in the highlight section.
calibre - New in calibre 5.0 (calibre-ebook.com)
<https://calibre-ebook.com/new-in/fourteen#:~:text=Highlights%20can%20be%20created%20by,of%20the%20calibre%20Content%20server.>

Good luck
