### ISSUE TITLE
CLI interface for the calibre-KiPEO plugin

### ISSUE THREAD

**Issue by Monirzadeh** [al1b/Calibre-KiPEO#2]
hi
can you add a CLI interface for the calibre-KiPEO plugin?

**Comment by al1b** [comment]
KiPEO is an `edit book plugin`. I still haven't found any documentation on Calibre website to find-out how we can write an editor plugin for Calibre which can also be supported in command-line.

https://manual.calibre-ebook.com/creating_plugins.html#edit-book-plugins

**Comment by Monirzadeh** [comment]
I am not sure but it can be useful:
https://www.mobileread.com/forums/showthread.php?t=259221
if you use this code get below error `calibre-debug --run-plugin "Kindle Persian E-book Optimizer(KiPEO) plugin" filename.azw3`

> The Kindle Persian E-book Optimizer(KiPEO) plugin plugin has no command line interface

**Comment by al1b** [comment]
@Monirzadeh I see, I will try to implement cli then.

**Comment by al1b** [comment]
I haven't test it yet, please test it @Monirzadeh.

**Comment by Monirzadeh** [comment]
terminal get me somthing like this
```
processing text/part0002.html
processing text/part0000.html
processing text/part0001.html

```
I don't know plugin overwrite file because when I move file to Kindle file has separate characters (publisher font)
I send file before and after run this command
calibre-debug --run-plugin "Kindle Persian E-book Optimizer(KiPEO) plugin" a.azw3


[awz3 before aftter.zip](https://github.com/al1b/Calibre-KiPEO/files/1144868/awz3.before.aftter.zip)
@al1b

**Comment by al1b** [comment]
@Monirzadeh I commited a new code. give it a try.

Accidentally ref the commit to another issue!
Here is the commit
https://github.com/al1b/Calibre-KiPEO/commit/6aaffef72be7a4475f8136a2d3ac192762166982

**Comment by Monirzadeh** [comment]
this work from CLI :)
but have a little problem in some characters that post in new issue
thank you

**Comment by al1b** [comment]
@Monirzadeh Will you post the issue? I'm gonna close this issue.
