### ISSUE TITLE
issue while installing plugin on calibre ubuntu 17.10

### ISSUE THREAD

**Issue by itsMahdi** [al1b/Calibre-KiPEO#6]
calibre, version 2.75.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/home/mahdi/Downloads/Calibre-KiPEO-master.zip' is invalid. It does not contain a top-level __init__.py file
```
calibre 2.75.1  embedded-python: False is64bit: True
Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty Linux ('64bit', '')
('Linux', '4.10.0-37-generic', '#41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017')
Python 2.7.13
Linux: ('Ubuntu', '17.04', 'zesty')
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 463, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 58, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in load
    plugin_name = self._locate_code(zf, path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 290, in _locate_code
    % path_to_zip_file)
InvalidPlugin: The plugin in u'/home/mahdi/Downloads/Calibre-KiPEO-master.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by al1b** [comment]
It's not a bug. You should not download the file from `Download Zip` in Github. Please download the released version or unpack the zipped file and repack it. 

As you can see in the picture below, the `py` files are not in the root of the zip.
![cap_02](https://user-images.githubusercontent.com/4526854/31864899-79973ca4-b772-11e7-8c3f-cd8de5f83882.PNG)

**Comment by amirslear** [comment]
Hi Ali
I got a problem with installing amazing KEIPO on windows. here is the error
calibre, version 3.38.1
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name reshape_book

calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.10586-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.10586')
Python 2.7.15+
Windows: ('10', '10.0.10586', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
ImportError: cannot import name reshape_book

**Comment by amirslear** [comment]
> Hi Ali
> I got a problem with installing amazing KEIPO on windows. here is the error
> calibre, version 3.38.1
> ERROR: Unhandled exception: ImportError:cannot import name reshape_book
> 
> calibre 3.38.1 embedded-python: True is64bit: False
> Windows-10-10.0.10586-SP0 Windows ('32bit', 'WindowsPE')
> 32bit process running on 64bit windows
> ('Windows', '10', '10.0.10586')
> Python 2.7.15+
> Windows: ('10', '10.0.10586', 'SP0', u'Multiprocessor Free')
> Interface language: None
> Traceback (most recent call last):
> File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
> File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
> File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
> File "site-packages\calibre\customize\zipplugin.py", line 200, in load
> File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
> File "calibre_plugins.dummy1.**init**", line 5, in 
> ImportError: cannot import name reshape_book

My Calibre version is 3.38.1
